/* Write your PL/SQL query statement below */
SELECT NAME AS RESULTS
FROM (
    SELECT U.NAME, COUNT(*) AS CNT
    FROM USERS U, MOVIERATING MR
    WHERE U.USER_ID = MR.USER_ID
    GROUP BY U.NAME
    ORDER BY CNT DESC, U.NAME ASC
)
WHERE ROWNUM <= 1
UNION ALL
SELECT TITLE AS RESULTS
FROM (
    SELECT M.TITLE, AVG(MR.RATING) AS AVER_RATING
    FROM MOVIES M, MOVIERATING MR
    WHERE M.MOVIE_ID = MR.MOVIE_ID
    AND MR.CREATED_AT LIKE '2020-02%'
    GROUP BY M.TITLE
    ORDER BY AVER_RATING DESC, M.TITLE ASC
)
WHERE ROWNUM <= 1
;