/* Write your PL/SQL query statement below */
SELECT 
    EMPLOYEE_ID, NAME, COUNT(*) AS REPORTS_COUNT, 
    ROUND(AVG(AGE), 0) AS average_age
FROM (
    SELECT 
        E1.REPORTS_TO, E1.AGE,
        E2.EMPLOYEE_ID, E2.NAME
    FROM EMPLOYEES E1, EMPLOYEES E2
    WHERE E1.REPORTS_TO = E2.EMPLOYEE_ID
)
GROUP BY EMPLOYEE_ID, NAME
ORDER BY EMPLOYEE_ID
