/* Write your PL/SQL query statement below */
SELECT E.EMPLOYEE_ID
FROM EMPLOYEES E, SALARIES S
WHERE E.EMPLOYEE_ID = S.EMPLOYEE_ID(+)
AND S.EMPLOYEE_ID IS NULL
UNION
SELECT S.EMPLOYEE_ID
FROM EMPLOYEES E, SALARIES S
WHERE E.EMPLOYEE_ID(+) = S.EMPLOYEE_ID
AND E.EMPLOYEE_ID IS NULL