/* Write your PL/SQL query statement below */
SELECT P.PRODUCT_NAME, SUM(UNIT) AS UNIT
FROM PRODUCTS P, ORDERS O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
AND TO_CHAR(ORDER_DATE, 'YYYY-MM') = '2020-02'
GROUP BY P.PRODUCT_NAME
HAVING SUM(UNIT) >= 100