/* Write your PL/SQL query statement below */
SELECT ID
FROM (
    SELECT
        ID, 
        LAG(RECORDDATE, 1) OVER(ORDER BY RECORDDATE) AS PREV_DATE,
        LAG(TEMPERATURE, 1) OVER(ORDER BY RECORDDATE) AS PREV_TEMPERATURE,
        RECORDDATE,
        TEMPERATURE
    FROM WEATHER
)
WHERE PREV_TEMPERATURE < TEMPERATURE
AND RECORDDATE - PREV_DATE = 1