/* Write your PL/SQL query statement below */
SELECT DISTINCT S.NAME
FROM (
SELECT C.COM_ID, C.NAME, C.CITY, O.ORDER_ID, O.SALES_ID
FROM COMPANY C, ORDERS O
WHERE C.COM_ID = O.COM_ID
) CO, SALESPERSON S
WHERE CO.SALES_ID(+) = S.SALES_ID
AND (CO.COM_ID IS NULL
OR S.NAME NOT IN (SELECT S.NAME
                  FROM COMPANY C, ORDERS O, SALESPERSON S
                  WHERE C.COM_ID = O.COM_ID
                  AND S.SALES_ID = O.SALES_ID
                  AND C.NAME = 'RED'))


