/* Write your PL/SQL query statement below */
SELECT
    DEPARTMENT, EMPLOYEE, SALARY 
FROM (
SELECT
    D.NAME AS DEPARTMENT,
    E.NAME AS EMPLOYEE,
    SALARY,
    DENSE_RANK() OVER(PARTITION BY D.ID
                    ORDER BY SALARY DESC) AS RAN
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPARTMENTID = D.ID
    )
WHERE RAN <= 3
