/* Write your PL/SQL query statement below */
SELECT CUSTOMER_NUMBER
FROM (
    SELECT CUSTOMER_NUMBER, COUNT(*) AS CNT
    FROM ORDERS
    GROUP BY CUSTOMER_NUMBER
    )
WHERE CNT = (SELECT MAX(CNT)
            FROM (
    SELECT CUSTOMER_NUMBER, COUNT(*) AS CNT
    FROM ORDERS
    GROUP BY CUSTOMER_NUMBER
    )
)

