/* Write your PL/SQL query statement below */
SELECT CUSTOMER_NUMBER
FROM (
    SELECT 
        CUSTOMER_NUMBER, COUNT(*), 
        DENSE_RANK() OVER(ORDER BY COUNT(*) DESC) AS RAN
    FROM ORDERS
    GROUP BY CUSTOMER_NUMBER
) 
WHERE RAN = 1
;
