/* Write your PL/SQL query statement below */
SELECT 
    TO_CHAR(T.TRANS_DATE, 'YYYY-MM') AS MONTH, T.COUNTRY,
    COUNT(T.ID) AS TRANS_COUNT,
    COUNT(A.ID) AS APPROVED_COUNT,
    NVL(SUM(T.AMOUNT), 0) AS TRANS_TOTAL_AMOUNT,
    NVL(SUM(A.AMOUNT), 0) AS APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS T, (SELECT * FROM TRANSACTIONS WHERE STATE = 'approved') A
WHERE T.ID = A.ID(+)
GROUP BY TO_CHAR(T.TRANS_DATE, 'YYYY-MM'), T.COUNTRY