/* Write your PL/SQL query statement below */
SELECT 
  U.USER_ID AS BUYER_ID, 
  TO_CHAR(JOIN_DATE, 'YYYY-MM-DD') AS JOIN_DATE, 
  NVL(COUNT(BUYER_ID), 0) AS ORDERS_IN_2019
FROM USERS U,(
  SELECT *
  FROM ORDERS
  WHERE EXTRACT(YEAR FROM ORDER_DATE) = 2019
) O_19
WHERE U.USER_ID = O_19.BUYER_ID(+)
GROUP BY U.USER_ID, U.JOIN_DATE