/* Write your PL/SQL query statement below */
SELECT NAME
FROM (
  SELECT E1.MANAGERID, E2.NAME
  FROM EMPLOYEE E1, EMPLOYEE E2
  WHERE E1.MANAGERID = E2.ID
  GROUP BY E1.MANAGERID, E2.NAME
  HAVING COUNT(*) >= 5
)
;
