/* Write your PL/SQL query statement below */

SELECT  
    STOCK_NAME,
    SUM(ADJ_PRICE) AS capital_gain_loss
FROM (
SELECT
    STOCK_NAME,
    OPERATION,
    CASE WHEN OPERATION = 'Buy' THEN -PRICE
    ELSE PRICE END AS ADJ_PRICE
FROM STOCKS
)
GROUP BY STOCK_NAME

