/* Write your PL/SQL query statement below */
SELECT S2.PRODUCT_ID, S1.FIRST_YEAR, S2.QUANTITY, S2.PRICE
FROM (
    SELECT SALE_ID, MIN(YEAR) OVER(PARTITION BY PRODUCT_ID) FIRST_YEAR
    FROM SALES
    ) S1, SALES S2
WHERE S1.SALE_ID = S2.SALE_ID
AND S1.FIRST_YEAR = S2.YEAR