/* Write your PL/SQL query statement below */
SELECT EMPLOYEE_ID, DEPARTMENT_ID
FROM EMPLOYEE
WHERE PRIMARY_FLAG = 'Y'
UNION
SELECT EMPLOYEE_ID, DEPARTMENT_ID
FROM (
    SELECT EMPLOYEE_ID, DEPARTMENT_ID, 
        COUNT(*) OVER(PARTITION BY EMPLOYEE_ID) AS CNT
    FROM EMPLOYEE
    )
WHERE CNT = 1