/* Write your PL/SQL query statement below */
SELECT 
    ROUND(SUM(CASE WHEN EVENT_DATE - FIRST_LOGIN = 1 THEN 1 ELSE 0 END) / COUNT(DISTINCT PLAYER_ID), 2) AS FRACTION 
FROM (
    SELECT 
        PLAYER_ID, 
        MIN(EVENT_DATE) OVER(PARTITION BY PLAYER_ID) AS FIRST_LOGIN,
        EVENT_DATE
    FROM ACTIVITY
)

