/* Write your PL/SQL query statement below */
SELECT E1.EMPLOYEE_ID
FROM (
  SELECT *
  FROM EMPLOYEES  
  WHERE SALARY < 30000
  AND MANAGER_ID IS NOT NULL
) E1, EMPLOYEES E2
WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID(+)
AND E2.EMPLOYEE_ID IS NULL
ORDER BY E1.EMPLOYEE_ID