/* Write your PL/SQL query statement below */
SELECT 
    ID,
    TO_CHAR(VISIT_DATE, 'YYYY-MM-DD') AS VISIT_DATE,
    PEOPLE
FROM (
SELECT
    ID,
    VISIT_DATE,
    LAG(PEOPLE,2) OVER(ORDER BY ID ASC) LAG2,
    LAG(PEOPLE,1) OVER(ORDER BY ID ASC) LAG1,
    PEOPLE,
    LEAD(PEOPLE,1) OVER(ORDER BY ID ASC) LEAD1,
    LEAD(PEOPLE,2) OVER(ORDER BY ID ASC) LEAD2
FROM STADIUM
) 
WHERE 
    (LAG2 >= 100 AND LAG1 >= 100 AND PEOPLE >= 100)
OR
    (LAG1 >= 100 AND PEOPLE >= 100 AND LEAD1 >= 100)
OR 
    (PEOPLE >= 100 AND LEAD1 >= 100 AND LEAD2 >= 100)