/* Write your PL/SQL query statement below */
SELECT 
    REQUEST_AT AS DAY, 
    ROUND(SUM(CASE WHEN STATUS LIKE 'cancelled%' THEN 1 ELSE 0 END) / COUNT(*), 2) AS "CANCELLATION RATE"
FROM TRIPS T
WHERE 'No' = ALL(
    SELECT BANNED
    FROM USERS U
    WHERE U.USERS_ID IN (T.CLIENT_ID, T.DRIVER_ID)
)
AND REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
GROUP BY REQUEST_AT
;