/* Write your PL/SQL query statement below */
SELECT CUSTOMER_ID, COUNT(VISIT_ID) AS COUNT_NO_TRANS
FROM (
  SELECT V.VISIT_ID, V.CUSTOMER_ID, T.TRANSACTION_ID, T.AMOUNT
  FROM VISITS V, TRANSACTIONS T
  WHERE V.VISIT_ID = T.VISIT_ID(+)
  AND T.TRANSACTION_ID IS NULL
)
GROUP BY CUSTOMER_ID
