/* Write your PL/SQL query statement below */

SELECT V.CUSTOMER_ID, COUNT(*) AS COUNT_NO_TRANS
FROM VISITS V, TRANSACTIONS T
WHERE V.VISIT_ID = T.VISIT_ID(+)
AND T.TRANSACTION_ID IS NULL
GROUP BY V.CUSTOMER_ID

