/* Write your PL/SQL query statement below */
SELECT 
  ROUND(100 * SUM(CASE WHEN ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE THEN 1 ELSE 0 END)/COUNT(DISTINCT CUSTOMER_ID), 2) AS IMMEDIATE_PERCENTAGE
FROM (
  SELECT
    ORDER_DATE, CUSTOMER_ID, 
    CUSTOMER_PREF_DELIVERY_DATE, 
    RANK() OVER(PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE) AS RK
  FROM DELIVERY)
WHERE RK = 1