/* Write your PL/SQL query statement below */
SELECT DISTINCT NUM AS CONSECUTIVENUMS
FROM (
    SELECT
        ID,
        LAG(NUM, 1) OVER(ORDER BY ID) AS PREV_NUM,
        NUM,
        LEAD(NUM, 1) OVER(ORDER BY ID) AS NEXT_NUM
    FROM LOGS
)
WHERE PREV_NUM = NUM
AND NUM = NEXT_NUM
